- hosts: localhost
  gather_facts: False
  connection: local
        
  tasks:
    - name: "Artifact URL of test results to Tower Workflows"
      set_stats:
        data:
          datacenter: "{{ datacenter }}"
          vm_name: "{{ vm_name }}"
          template: "{{ template }}"
          vm_size: "{{ vm_size }}"
          vmcluster: "{{ vmcluster }}"
          ip_addr: "{{ ip_addr }}"
          net_mask: "{{ net_mask }}"
          gate_way: "{{ gate_way }}"
